/**
 * Converts PM agent dataModel to Supabase-compatible PostgreSQL DDL.
 *
 * Input shape (from PM_SYSTEM prompt):
 *   dataModel: [{ entity: "Post", fields: [{ name: "title", type: "text" }] }]
 *
 * Output: CREATE TABLE IF NOT EXISTS ... statements with sane defaults.
 */

const TYPE_MAP = {
  uuid: 'UUID',
  text: 'TEXT',
  string: 'TEXT',
  varchar: 'TEXT',
  number: 'NUMERIC',
  numeric: 'NUMERIC',
  integer: 'INTEGER',
  int: 'INTEGER',
  bigint: 'BIGINT',
  boolean: 'BOOLEAN',
  bool: 'BOOLEAN',
  timestamp: 'TIMESTAMPTZ',
  date: 'TIMESTAMPTZ',
  datetime: 'TIMESTAMPTZ',
  json: 'JSONB',
  jsonb: 'JSONB',
  array: 'JSONB',
};

function toSnakeCase(str) {
  return str
    .replace(/([A-Z])/g, '_$1')
    .toLowerCase()
    .replace(/^_/, '')
    .replace(/[^a-z0-9_]/g, '_');
}

function toTableName(entity) {
  const snake = toSnakeCase(entity);
  return snake.endsWith('s') ? snake : snake + 's';
}

function resolveType(type = 'text') {
  return TYPE_MAP[type.toLowerCase()] || 'TEXT';
}

/**
 * @param {Array<{entity: string, fields: Array<{name: string, type: string, required?: boolean, unique?: boolean}>}>} dataModel
 * @returns {{ sql: string, tables: string[] }}
 */
export function generateSchema(dataModel) {
  if (!Array.isArray(dataModel) || dataModel.length === 0) return { sql: '', tables: [] };

  const tables = [];
  const blocks = [];

  for (const entity of dataModel) {
    if (!entity?.entity) continue;
    const tableName = toTableName(entity.entity);
    tables.push(tableName);

    const fields = Array.isArray(entity.fields) ? entity.fields : [];

    const hasId = fields.some(f => f.name?.toLowerCase() === 'id');
    const hasCreatedAt = fields.some(f => f.name?.toLowerCase() === 'created_at');
    const hasUpdatedAt = fields.some(f => f.name?.toLowerCase() === 'updated_at');

    const cols = [];

    // Always add UUID primary key if not declared
    if (!hasId) {
      cols.push(`  id UUID PRIMARY KEY DEFAULT gen_random_uuid()`);
    }

    for (const field of fields) {
      if (!field?.name) continue;
      const colName = toSnakeCase(field.name);
      const colType = resolveType(field.type);
      const notNull = field.required ? ' NOT NULL' : '';
      const unique = field.unique ? ' UNIQUE' : '';

      if (colName === 'id') {
        cols.push(`  id UUID PRIMARY KEY DEFAULT gen_random_uuid()`);
      } else {
        cols.push(`  ${colName} ${colType}${notNull}${unique}`);
      }
    }

    // Auto timestamps
    if (!hasCreatedAt) cols.push(`  created_at TIMESTAMPTZ NOT NULL DEFAULT now()`);
    if (!hasUpdatedAt) cols.push(`  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()`);

    const block = [
      `-- Table: ${tableName}`,
      `CREATE TABLE IF NOT EXISTS ${tableName} (`,
      cols.join(',\n'),
      `);`,
      ``,
      `-- RLS (activate per your auth strategy)`,
      `ALTER TABLE ${tableName} ENABLE ROW LEVEL SECURITY;`,
    ].join('\n');

    blocks.push(block);
  }

  const sql = [
    `-- Auto-generated by Huggy Studio`,
    `-- Run this in your Supabase SQL Editor`,
    ``,
    ...blocks,
  ].join('\n');

  return { sql, tables };
}
